@startuml "users"

entity "users" as users {
    * id : uuid [primary key]
    * username : varchar(40) [unique]
    * password : varchar(40)
    * name : varchar(50)
    * role : varchar(15)
    * status : varchar(10)
    * created_at : datetime
    * updated_at : datetime
    * deleted_at : datetime
}

@enduml